language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - $HOME/maintainer-quality-tools/travis/travis_install_nightly 6.1
  - pip install coveralls flake8
  - git clone https://github.com/OCA/stock-logistics-tracking -b 6.1
  - git clone https://github.com/OCA/stock-logistics-barcode -b 6.1
services:
  - postgresql

script:
    - travis_run_flake8
    - travis_run_tests 6.1 openerp_test $HOME/stock-logistics-tracking $HOME/stock-logistics-barcode

after_success:
  coveralls
