language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
 - git clone https://github.com/gurneyalex/maintainer-quality-tools.git $HOME/maintainer-quality-tools
 - git clone https://github.com/OCA/stock-logistics-tracking.git -b 7.0 $HOME/stock-logistics-tracking
 - git clone https://github.com/OCA/stock-logistics-barcode.git -b 7.0 $HOME/stock-logistics-barcode

services:
  - postgresql

env:
 - PATH=$HOME/maintainer-quality-tools/travis:$PATH

install:
    - $HOME/maintainer-quality-tools/travis/travis_install_nightly.sh 7.0
    - pip install coveralls flake8

script:
    - travis_run_flake8
    - travis_run_tests.sh 7.0 openerp_test $HOME/stock-logistics-tracking $HOME/stock-logistics-barcode

after_success:
  coveralls

notifications:
  email:
    - alexandre.fayolle@camptocamp.com
